### ISSUE TITLE
Pagure API calls returning HTMLs -> cluttered log

### ISSUE THREAD

**Issue by jpopelka** [packit/hardly#53] opened 2022-03-24 11:58 UTC
When syncing CI results from Fedora Pagure, at some point, probably in [SyncFromPagurePRHandler.__init__()](https://github.com/packit/hardly/blob/159f66731a9241217a338bc39b6ced5218b27687/hardly/handlers/distgit.py#L267) our code tries to get packit config from the dist-git repo and each call (there are 5-ish of them) to Pagure API results in

```html
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>Page not found :'( - src.fedoraproject.org</title>
        <link rel="shortcut icon" type="image/vnd.microsoft.icon"
        href="/theme/static/favicon.ico?version=5.13.3"/>
    <link href="/theme/static/fedora-bootstrap-1.3.0/fedora-bootstrap.min.css?version=5.13.3"
        type="text/css" rel="stylesheet" />
    <link href="/theme/static/fonts/fonts.css?version=5.13.3"
        rel="stylesheet" type="text/css" />
    <link href="/theme/static/fonts/hack_fonts/css/hack-extended.min.css?version=5.13.3"
        type="text/css" rel="stylesheet" />
    <link href="/theme/static/theme.css?version=5.13.3"
        type="text/css" rel="stylesheet" />

    <link type="text/css" rel="stylesheet" nonce="RbdvqjyR32cNizVtOrc6gJgOh" href="/static/vendor/font-awesome/font-awesome.css?version=5.13.3"/>
    <link type="text/css" rel="stylesheet" nonce="RbdvqjyR32cNizVtOrc6gJgOh" href="/static/pagure.css?version=5.13.3"/>
  </head>
  <body id="error">

    <!-- start masthead -->
    <nav class="navbar navbar-light masthead p-0 navbar-expand">
      <div class="container">
        <a href="/" class="navbar-brand">
        <img height="40" src="/theme/static/pagure-logo.png?version=5.13.3"
             alt="pagure Logo" id="pagureLogo"/>
        </a>
        <ul class="navbar-nav ml-auto">



          <li class="nav-item">
            <a class="btn btn-primary" href="/login/?next=https://src.fedoraproject.org/rpms/python-httpretty/raw/d0143f413982f696550bddfda1a0e0cb8466c855/f/.distro/source-git.yaml">Log In</a>
          </li>
        </ul>
      </div>
    </nav>
    <!-- close masthead-->

    <div class="bodycontent">


<div class="container p-t-3">
  <div class="row">
    <div class="col-md-8">
      <h2>Page not found (404)</h2>
      <p>With the message:</p>
      <div class="card-block">
      <p>File not found</p>
      </div>
      <p>You have either entered a bad URL or the page has moved, removed, or otherwise rendered unavailable.<br/>
      Please use the main navigation menu to get (re)started.</p>
    </div>
  </div>
</div>
    </div>

        <div class="footer pt-4 text-white">
        <div class="container">
            <div class="d-flex align-items-center">
                <div>
                    <div>Powered by <a href="https://pagure.io/pagure" class="notblue">Pagure</a> 5.13.3</div>
                    <div>
                        <a href="https://docs.pagure.org/pagure/usage/index.html" class="notblue">Documentation</a> &bull;
                        <a href="https://pagure.io/pagure/new_issue" class="notblue">File an Issue</a> &bull;
                        <a href="/about">About this Instance</a> &bull;
                        <a href="/ssh_info" class="notblue">SSH Hostkey/Fingerprint</a>
                    </div>
                </div>
                <div class="ml-auto text-right">
                    <div>&copy; Red Hat, Inc. and others.</div>
                </div>
            </div>
        </div>
    </div>


    <script type="text/javascript" nonce="RbdvqjyR32cNizVtOrc6gJgOh" src="/static/vendor/jquery/jquery.min.js?version=5.13.3"></script>

    <script src="/static/vendor/bootstrap/bootstrap.bundle.min.js?version=5.13.3"></script>

    <script type="text/javascript" nonce="RbdvqjyR32cNizVtOrc6gJgOh">
      $('[data-toggle="tooltip"]').tooltip({placement : 'bottom'});
      $(".cancel_btn").click(function() {
        history.back();
      });
    </script>

</body>
</html>
```

which clutters the log. Not sure whether to fix it here (`hardly`) or in `packit` or in `ogr`.

**Comment by TomasTomecek** [comment] 2022-03-25 07:50
I think it would make sense to start doing only a single (or two) request(s): check for `.packit.y[a]ml`

Do we a sentry traceback - it would be nice to catch this in ogr and wrap with the GitForgeException

**Comment by lachmanfrantisek** [comment] 2022-09-08 11:15
Probably a duplicate of https://github.com/packit/packit-service/issues/1629 and can be fixed in ogr.

**Closed** 2022-09-08 13:01 UTC
